[env:esp32-s3-touch-lcd-1_47]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Configuración crítica de Memoria Externa (PSRAM)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    moononournation/GFX Library for Arduino @ 1.4.9
    bitbank2/PNGdec @ ^1.1.6
    bblanchon/ArduinoJson @ ^6.21.3

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D BOARD_HAS_PSRAM 
    -D CORE_DEBUG_LEVEL=0
